# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4fa729535dcd069a6f77d456ce74551c"
name = "prototype-app"
handle = "prototype-app-8"
application_url = "https://scout-route-intersection-vs.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://scout-route-intersection-vs.trycloudflare.com/auth/callback", "https://scout-route-intersection-vs.trycloudflare.com/auth/shopify/callback", "https://scout-route-intersection-vs.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
